import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;

/**
 * A Vending Machine program, designed to dispense drinks for a customer
 * complete for both a cash paying customer and a pre-pay loyalty
 * card customer.
 * 
 * Loyalty card customer receives a discount on their product. They can
 * also opt to pay with cash, whilst still receiving the discount.
 * 
 * Complete with GUI.
 * 
 * @author Jamie McGrath
 */
public class VendingMachineGUI extends JFrame {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form VendingMachineGUI
     */
    public VendingMachineGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//**** Initialising variables ****//
    	jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        group = new ButtonGroup();
        coke = new ImageIcon(".\\images\\coke.png");
        lemon = new ImageIcon(".\\images\\lemonade.png");
        tango = new ImageIcon(".\\images\\tango.png");
        water = new ImageIcon(".\\images\\water.png");
        pepsi = new ImageIcon(".\\images\\pepsi.png");
        sprite = new ImageIcon(".\\images\\sprite.png");
        cokeRb = new JToggleButton(coke);
        waterRb = new JToggleButton(water);
        lemonadeRb = new JToggleButton(lemon);
        pepsiRb = new JToggleButton(pepsi);
        tangoRb = new JToggleButton(tango);
        spriteRb = new JToggleButton(sprite);
        waterPrice = new JTextField();
        lemonPrice = new JTextField();
        pepsiPrice = new JTextField();
        cokePrice = new JTextField();
        tangoPrice = new JTextField();
        spritePrice = new JTextField();
        purchaseBtn = new JButton();
        clearBtn = new JButton();
        cancelBtn = new JButton();
        moneyTf = new JLabel("0.00");
        changeTf = new JLabel("0.00");
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        cardBtn = new JButton();
        cardBtnPurchase = new JButton();
        cokeLbl = new JLabel();
        lemonLbl = new JLabel();
        tangoLbl = new JLabel();
        waterLbl = new JLabel();
        spriteLbl = new JLabel();
        pepsiLbl = new JLabel();
        fivePence = new JButton();
        twoPound = new JButton();
        fiftyPence = new JButton();
        tenPence = new JButton();
        twentyPence = new JButton();
        onePound = new JButton();
        //**** end of variable initialisation ****//

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        //**** styling the components in the GUI ****//
        jLabel1.setFont(new Font("Bauhaus 93", 0, 36));
        jLabel1.setText("Drinks R' Us");

        jPanel1.setBorder(BorderFactory.createTitledBorder("Select a Product"));

        waterPrice.setEditable(false);
        waterPrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        waterPrice.setHorizontalAlignment(JTextField.CENTER);
        waterPrice.setText("£1.00");

        lemonPrice.setEditable(false);
        lemonPrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        lemonPrice.setHorizontalAlignment(JTextField.CENTER);
        lemonPrice.setText("£1.20");

        pepsiPrice.setEditable(false);
        pepsiPrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        pepsiPrice.setHorizontalAlignment(JTextField.CENTER);
        pepsiPrice.setText("£1.30");

        cokePrice.setEditable(false);
        cokePrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        cokePrice.setHorizontalAlignment(JTextField.CENTER);
        cokePrice.setText("£1.50");

        tangoPrice.setEditable(false);
        tangoPrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        tangoPrice.setHorizontalAlignment(JTextField.CENTER);
        tangoPrice.setText("£1.40");

        spritePrice.setEditable(false);
        spritePrice.setFont(new Font("Lucida Sans Typewriter", 1, 10));
        spritePrice.setHorizontalAlignment(JTextField.CENTER);
        spritePrice.setText("£1.20");
        
        cokeLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        cokeLbl.setHorizontalAlignment(SwingConstants.CENTER);
        cokeLbl.setText("COKE");

        lemonLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        lemonLbl.setHorizontalAlignment(SwingConstants.CENTER);
        lemonLbl.setText("LEMONADE");

        tangoLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        tangoLbl.setHorizontalAlignment(SwingConstants.CENTER);
        tangoLbl.setText("TANGO");

        waterLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        waterLbl.setHorizontalAlignment(SwingConstants.CENTER);
        waterLbl.setText("WATER");

        pepsiLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        pepsiLbl.setHorizontalAlignment(SwingConstants.CENTER);
        pepsiLbl.setText("PEPSI");

        spriteLbl.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        spriteLbl.setHorizontalAlignment(SwingConstants.CENTER);
        spriteLbl.setText("SPRITE");
        //**** end of styling ****//

        //**** start of the GUI layout 1 ****//
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(waterRb, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(waterPrice)
                    .addComponent(cokePrice)
                    .addComponent(cokeRb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cokeLbl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waterLbl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lemonadeRb, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lemonPrice)
                    .addComponent(pepsiRb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pepsiPrice)
                    .addComponent(lemonLbl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pepsiLbl, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tangoPrice)
                    .addComponent(tangoRb, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(spriteRb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spritePrice)
                    .addComponent(tangoLbl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spriteLbl, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemonadeRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tangoRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeLbl)
                    .addComponent(lemonLbl)
                    .addComponent(tangoLbl))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cokePrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemonPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tangoPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(spriteRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsiRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterRb, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(waterLbl)
                    .addComponent(pepsiLbl)
                    .addComponent(spriteLbl))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(waterPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsiPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(spritePrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        /** 
         * add each product button to a button group, so app
         * will deselect current selection on a new selection.
         */ 
        group.add(cokeRb);
        group.add(lemonadeRb);
        group.add(tangoRb);
        group.add(waterRb);
        group.add(spriteRb);
        group.add(pepsiRb);
        //**** end of GUI layout 1 ****//

        //**** start of action performed for the button clicks ****//
        purchaseBtn.setText("Purchase");
        purchaseBtn.setBackground(Color.GREEN);
        purchaseBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setBackground(Color.RED);
        cancelBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        moneyTf.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        jLabel2.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        changeTf.setFont(new Font("Lucida Sans Typewriter", 0, 14));
        jLabel3.setFont(new Font("Lucida Sans Typewriter", 0, 14));

        jLabel2.setText("Insert Cash..");

        jLabel3.setText("Card Balance..");

        cardBtn.setText("Pay with Loyalty Card");
        cardBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cardBtnPurchaseActionPerformed(evt);
            }
        });

        cardBtnPurchase.setText("Scan Loyalty Card");
        cardBtnPurchase.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cardBtnActionPerformed(evt);
            }
        });
        
        fivePence.setText("5p");
        fivePence.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
            	fivePenceActionPerformed(evt);
            }
        });
        
        tenPence.setText("10p");
        tenPence.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		tenPenceActionPerformed(evt);
        	}
        });
        
        twentyPence.setText("20p");
        twentyPence.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		twentyPenceActionPerformed(evt);
        	}
        });
        
        fiftyPence.setText("50p");
        fiftyPence.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		fiftyPenceActionPerformed(evt);
        	}
        });
        
        onePound.setText("£1");
        onePound.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		onePoundActionPerformed(evt);
        	}
        });

        twoPound.setText("£2");
        twoPound.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                twoPoundActionPerformed(evt);
            }
        });
        //**** end of action performed for the button clicks ****//
        
        //**** start of GUI layout 2 ****//
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBtnPurchase, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(moneyTf, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeTf, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelBtn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearBtn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchaseBtn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fiftyPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(onePound, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(twoPound, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fivePence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(twentyPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cardBtn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(moneyTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(changeTf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(fivePence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(twentyPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(twoPound, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiftyPence, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(onePound, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseBtn, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cardBtn, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBtnPurchase, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>  
    
	// Variables declaration - do not modify
    private ButtonGroup group;
    private static JButton cancelBtn, cardBtn, cardBtnPurchase, clearBtn, purchaseBtn,
    					   fivePence, tenPence, twentyPence, fiftyPence, onePound, twoPound;
    private static JTextField cokePrice, lemonPrice, pepsiPrice, 
    						  spritePrice, tangoPrice, waterPrice;
    protected static JLabel moneyTf, changeTf;
    private static JToggleButton cokeRb, lemonadeRb, pepsiRb, spriteRb, tangoRb, waterRb;
    private JLabel jLabel1, jLabel2, jLabel3;
    private JPanel jPanel1;
    private ImageIcon coke, lemon, tango, water, pepsi, sprite;
    private JLabel cokeLbl, lemonLbl, tangoLbl, waterLbl, spriteLbl, pepsiLbl;
    // End of variables declaration                                     

    private void cardBtnActionPerformed(ActionEvent evt) {
    	new CustomerDiscount().cardBalance();
    }
    
    private void cardBtnPurchaseActionPerformed(ActionEvent evt) {
    	new CardCustomer().cardProduct();
    }
    
    private void cancelBtnActionPerformed(ActionEvent evt) {
    	JOptionPane.showMessageDialog(cancelBtn, "Purchase Cancelled");
        System.exit(0);
    }                                         

    private void purchaseBtnActionPerformed(ActionEvent evt) {
    	new CashCustomer().selectedProduct();
    }

    private void clearBtnActionPerformed(ActionEvent evt) {
    	group.clearSelection();
        
        new KeyPad().clearBalance();
        
        moneyTf.setText("0.00");
        changeTf.setText("0.00");
    }
    
    private void fivePenceActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getFivePence();
    }

    private void tenPenceActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getTenPence();
    }

    private void twentyPenceActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getTwentyPence();
    }

    private void fiftyPenceActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getFiftyPence();
    }

    private void onePoundActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getOnePence();
    }

    private void twoPoundActionPerformed(ActionEvent evt) {
    	KeyPad keyPad = new KeyPad();
		keyPad.getTwoPence();
    }
    
    public static JTextField getSpritePrice() {
		return spritePrice;
	}

	public static JTextField getCokePrice() {
		return cokePrice;
	}

	public static JTextField getWaterPrice() {
		return waterPrice;
	}

	public static JTextField getTangoPrice() {
		return tangoPrice;
	}

	public static JTextField getLemonPrice() {
		return lemonPrice;
	}

	public static JTextField getPepsiPrice() {
		return pepsiPrice;
	}

	public static JToggleButton getSpriteRb() {
		return spriteRb;
	}

	public static JToggleButton getCokeRb() {
		return cokeRb;
	}

	public static JToggleButton getWaterRb() {
		return waterRb;
	}

	public static JToggleButton getTangoRb() {
		return tangoRb;
	}

	public static JToggleButton getLemonadeRb() {
		return lemonadeRb;
	}

	public static JToggleButton getPepsiRb() {
		return pepsiRb;
	}
	
	public static JButton getPurchaseBtn() {
		return purchaseBtn;
	}
	
	public static String getChangeTf() {
		return changeTf.getText();
	}
	
	public static String getMoneyTf() {
		return moneyTf.getText();
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VendingMachineGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VendingMachineGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VendingMachineGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VendingMachineGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachineGUI().setVisible(true);
            }
        });
    }
              
}
